# Site wide configuration

title:            RABBIT LEARN
locale:           en_US
url:              http://therabbitteam.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Rabit Team
  avatar: bio/bio_quan.jpg
  bio: "Describe about team"
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

prose:
  rooturl: '_posts'
  siteurl: 'http://therabbitteam.github.io'
  media: 'images/posts'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "modified"
        field:
          element: "hidden"
          label: "CURRENT_DATETIME"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Rabbit Team"
              value: "rabbit_team"
            - name: "Hoàng Quân"
              value: "hoang_quan"
  #     - name: "comments"
  #       field:
  #         element: "checkbox"
  #         label: "Allow user to comment on this post"
  #     - name: "tags"
  #       field:
  #         element: "multiselect"
  #         label: "Add Tags"
  #         placeholder: "Choose Tags"
  #         alterable: true
  #         options:
  #           - name: "RHM5"
  #             value: "rhm5"
  #           - name: "RHM4"
  #             value: "RHM4"
